<a href="https://colab.research.google.com/github/Pedroct06/Estudos-Pandas/blob/main/EstudoPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [7]:
vendas_df = pd.read_excel("Vendas.xlsx")
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

In [11]:
display(vendas_df.describe())

,Código Venda,Data,Quantidade,Valor Unitário,Valor Final
count,93910.000000,93910,93910.000000,93910.000000,93910.000000
mean,32464.762155,2019-06-16 23:52:28.265360896,2.166553,191.725886,414.862656
min,1.000000,2019-01-01 00:00:00,1.000000,30.000000,30.000000
25%,16204.000000,2019-03-26 00:00:00,1.000000,100.000000,156.000000
50%,32367.000000,2019-06-17 00:00:00,2.000000,155.000000,274.000000
75%,48793.750000,2019-09-08 00:00:00,3.000000,248.000000,524.000000
max,65014.000000,2019-11-30 00:00:00,5.000000,750.000000,3750.000000
std,18809.007093,NaN,1.258732,145.215519,434.846228

In [14]:
produtos = vendas_df[['Produto', 'ID Loja']]
display(produtos)

                 Produto              ID Loja
0         Sapato Estampa   Iguatemi Esplanada
1               Camiseta   Iguatemi Esplanada
2          Sapato Xadrez   Iguatemi Esplanada
3                Relógio       Norte Shopping
4           Chinelo Liso       Norte Shopping
...                  ...                  ...
93905     Mochila Xadrez  Shopping Vila Velha
93906  Pulseira Listrado    Ribeirão Shopping
93907     Cueca Listrado    Ribeirão Shopping
93908     Pulseira Linho     Shopping Morumbi
93909      Casaco Xadrez     Shopping Morumbi

[93910 rows x 2 columns]

In [19]:
#pegar uma linha apenas
display(vendas_df.loc[1:5])

#pegar linhas de uma condição
display(vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping'])
vendas_NorteShopping_df = vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping']

#pegar varias linhas e colunas
vendas_NorteShopping_df = vendas_df.loc[vendas_df['ID Loja'] == 'Norte Shopping', ["ID Loja","Produto", "Quantidade"]]
display(vendas_NorteShopping_df)

#pegar um valor em específico
print(vendas_df.loc[1,"Produto"])

Camiseta

In [22]:
#Adicionar coluna a partir de uma coluna que já existe
vendas_df['Comissão'] = vendas_df['Valor Final'] * 0.05
#display(vendas_df)


#criar uma coluna com valor padrão
vendas_df.loc[:,'Imposto'] = 0
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Imposto
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00,0
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55,0
...,...,...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566,28.30,0
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158,7.90,0
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201,10.05,0
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570,28.50,0
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036,51.80,0

In [36]:
vendas_dez_df = pd.read_excel("Vendas - Dez.xlsx")
#display(vendas_dez_df)

vendas_df = pd.concat([vendas_df,vendas_dez_df])
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN

In [38]:
#Excluir linhas e colunas (axis = 0 - linhas, axis = 1 - colunas)
vendas_df = vendas_df.drop('Imposto', axis = 1)
display(vendas_df)

#Excluir linhas/colunas vazias
vendas_df = vendas_df.dropna(how = "all",axis = 1)

#deletar linhas que possuem pelo menos um valor vazio
vendas_df = vendas_df.dropna()
display(vendas_df)

#preencher valores vazios
#com a média
vendas_df["Comissão"] = vendas_df['Comissão'].fillna(vendas_df['Comissão'].mean())
display(vendas_df)

#com o ultimo valor
vendas_df = vendas_df.ffill()

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.900000
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.000000
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.400000
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.000000
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.550000
...,...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,20.743133
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,20.743133
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,20.743133
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,20.743133
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,20.743133

In [43]:
#value counts
#transacoes_loja = vendas_df['ID Loja'].value_counts()
#print(transacoes_loja)

#group by
faturamento_produto = vendas_df[['Produto','Valor Final']].groupby("Produto").mean()
display(faturamento_produto)

                  Valor Final
Produto
Bermuda            326.830732
Bermuda Estampa    363.708229
Bermuda Linho      429.934641
Bermuda Liso       340.360494
Bermuda Listrado   345.798349
...                       ...
Tênis Estampa      544.914286
Tênis Linho        633.656471
Tênis Liso         571.051745
Tênis Listrado     571.296912
Tênis Xadrez       541.489988

[120 rows x 1 columns]

In [45]:
gerentes_df = pd.read_excel("Gerentes.xlsx")
#display(gerentes_df)

#mesclar dois dataframes
vendas_df = vendas_df.merge(gerentes_df)
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão,Gerente
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.900000,Salvador
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.000000,Salvador
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.400000,Salvador
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.000000,Joana
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.550000,Joana
...,...,...,...,...,...,...,...,...,...
100994,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,20.743133,Andressa
100995,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,20.743133,Andressa
100996,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,20.743133,Andressa
100997,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,20.743133,Fábio
100998,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,20.743133,Fábio